In [2]:
import pandas as pd
import numpy as np
from pandas import DataFrame
from pyexcel_ods import save_data
from collections import OrderedDict

In [3]:
# The empty dataframe

initial_df: DataFrame

In [4]:
# Save the file on the data, verifying before if its not overwriting something
try:
    initial_df = pd.read_excel("./data/original_data_aracau.ods", engine="odf")
except FileNotFoundError as error:
    print("The file already exist")
    raise Exception("The file already exist")

In [5]:
# Read the file with the original changes
# initial_df = pd.read_excel("./data/original_dados_aracau.ods", engine="odf")

initial_df

,Unnamed: 0,Fluxo Escolar - Label,Campus (Nome),Curso+Modalidade,Matrícula retida?,Ingressantes em (Período Letivo),Modalidade de Ensino,Modalidade do Curso,Nível de Ensino,Período Letivo,...,É ingressante? (rótulo),É matrícula retida neste período letivo?,Última Alteração de Situação,CH,CH. Disc. Obrigatórias,CH. Disc. Optativas,Duracao curso,Idade (Hoje),Periodos Cursados,Período Letivo da Mudança de Situação
0,0,Em Curso,Acaraú,LÍNGUA INGLESA,Dentro do prazo,20192,Presencial,Fic,Básico,2019/2,...,Ingressante,Não Retida,2019-11-07,160,160,0,2,35,1,2019/2
1,2,Evadidos,Acaraú,TÉCNICO EM AQUICULTURA (Subsequente),Dentro do prazo,20151,Presencial,Subsequente,Técnico,2015/2,...,Veterano,Não Retida,2016-02-26,1240,1240,0,4,28,2,2015/2
2,3,Formados,Acaraú,XADREZ BÁSICO,Dentro do prazo,20172,Presencial,Fic,Básico,2017/2,...,Ingressante,Não Retida,2018-05-16,60,60,0,1,22,1,2017/2
3,5,Formados,Acaraú,TÉCNICO EM EVENTOS (Subsequente),Fora do prazo,20172,Presencial,Subsequente,Técnico,2017/2,...,Ingressante,Não Retida,2018-11-09,800,800,0,2,23,2,NaN
4,7,Evadidos,Acaraú,LICENCIATURA EM CIÊNCIAS BIOLÓGICAS,Dentro do prazo,20152,Presencial,Licenciatura,Graduação,2016/1,...,Veterano,Não Retida,2016-12-01,2940,2860,80,8,23,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3315,8434,Formados,Acaraú,MATEMÁTICA BÁSICA,Dentro do prazo,20182,Presencial,Fic,Básico,2018/2,...,Ingressante,Não Retida,2019-05-09,40,40,0,1,21,1,2018/2
3316,8435,Em Curso,Acaraú,LÍNGUA INGLESA,Dentro do prazo,20192,Presencial,Fic,Básico,2019/2,...,Ingressante,Não Retida,2019-10-16,160,160,0,2,26,1,NaN
3317,8437,Evadidos,Acaraú,LÍNGUA INGLESA,Fora do prazo,20172,Presencial,Fic,Básico,2018/1,...,Veterano,Retida,2018-06-19,160,160,0,2,28,2,2018/1
3318,8443,Formados,Acaraú,TÉCNICO EM AQUICULTURA (Subsequente),Fora do prazo,20161,Presencial,Subsequente,Técnico,2018/2,...,Veterano,Retida,2018-12-28,1240,1240,0,4,22,6,2018/2
3319,8445,Evadidos,Acaraú,LICENCIATURA EM CIÊNCIAS BIOLÓGICAS,Dentro do prazo,20182,Presencial,Licenciatura,Graduação,2018/2,...,Ingressante,Não Retida,2019-06-14,3440,3200,240,8,19,2,NaN

In [6]:
# Droped 10 collumns

formated_df = initial_df.drop(
    columns=[
        "Curso+Modalidade",
        "Modalidade de Ensino",

        "Município do Campus",
        "Campus",
        "Período Letivo",

        "Município, UF",
        "Nivel de Ensino - sem hierar",
        "É ingressante?",
        "É ingressante? (rótulo)",
        "Unnamed: 0",
    ]
)

In [7]:
formated_df

,Fluxo Escolar - Label,Campus (Nome),Matrícula retida?,Ingressantes em (Período Letivo),Modalidade do Curso,Nível de Ensino,Tipo de Modalidade (grupo),Cidade Aluno,Cód. da Matriz,Cód. do Curso,...,Tipo_Escola_Origem,É matrícula retida neste período letivo?,Última Alteração de Situação,CH,CH. Disc. Obrigatórias,CH. Disc. Optativas,Duracao curso,Idade (Hoje),Periodos Cursados,Período Letivo da Mudança de Situação
0,Em Curso,Acaraú,Dentro do prazo,20192,Fic,Básico,NaN,Acaraú,7277,111024,...,E,Não Retida,2019-11-07,160,160,0,2,35,1,2019/2
1,Evadidos,Acaraú,Dentro do prazo,20151,Subsequente,Técnico,Educação Profissional,Acaraú,5158,11200,...,E,Não Retida,2016-02-26,1240,1240,0,4,28,2,2015/2
2,Formados,Acaraú,Dentro do prazo,20172,Fic,Básico,NaN,Acaraú,10126,111030,...,E,Não Retida,2018-05-16,60,60,0,1,22,1,2017/2
3,Formados,Acaraú,Fora do prazo,20172,Subsequente,Técnico,Educação Profissional,Marco,7083,11204,...,E,Não Retida,2018-11-09,800,800,0,2,23,2,NaN
4,Evadidos,Acaraú,Dentro do prazo,20152,Licenciatura,Graduação,Regular,Acaraú,4496,11401,...,M,Não Retida,2016-12-01,2940,2860,80,8,23,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3315,Formados,Acaraú,Dentro do prazo,20182,Fic,Básico,NaN,Acaraú,12389,111034,...,E,Não Retida,2019-05-09,40,40,0,1,21,1,2018/2
3316,Em Curso,Acaraú,Dentro do prazo,20192,Fic,Básico,NaN,Acaraú,7277,111024,...,E,Não Retida,2019-10-16,160,160,0,2,26,1,NaN
3317,Evadidos,Acaraú,Fora do prazo,20172,Fic,Básico,NaN,Cruz,7277,111024,...,E,Retida,2018-06-19,160,160,0,2,28,2,2018/1
3318,Formados,Acaraú,Fora do prazo,20161,Subsequente,Técnico,Educação Profissional,Acaraú,5158,11200,...,E,Retida,2018-12-28,1240,1240,0,4,22,6,2018/2
3319,Evadidos,Acaraú,Dentro do prazo,20182,Licenciatura,Graduação,Regular,Acaraú,12166,11401,...,E,Não Retida,2019-06-14,3440,3200,240,8,19,2,NaN

In [8]:
# count null values by column
nan_counts = formated_df.isna().sum()
nan_counts

Fluxo Escolar - Label                          0
Campus (Nome)                                  0
Matrícula retida?                              0
Ingressantes em (Período Letivo)               0
Modalidade do Curso                            0
Nível de Ensino                                0
Tipo de Modalidade (grupo)                   580
Cidade Aluno                                  78
Cód. da Matriz                                 0
Cód. do Curso                                  0
Data Final Período                             3
Data Início Período                            4
Data Última Alteração Matrícula                0
Dt Ref Início Matrícula                        0
Dt Ref Início Período Letivo                   0
Estado Aluno                                  78
Estrutura Etária                               0
Etnia                                          0
Faixa Etária                                   0
Forma de Ingresso                              0
Forma de Oferta (grupo)                        0
Ingressantes em  (Ano Letivo)                  0
Num Seq deste Período Letivo                   0
Periodo Letivo (Num)                           0
Previsão de Término (Letivo)                   0
Reserva vaga                                 373
Sexo                                           0
Tipo de Modalidade                           580
Tipo_Escola_Origem                           341
É matrícula retida neste período letivo?       0
Última Alteração de Situação                   0
CH                                             0
CH. Disc. Obrigatórias                         0
CH. Disc. Optativas                            0
Duracao curso                                  0
Idade (Hoje)                                   0
Periodos Cursados                              0
Período Letivo da Mudança de Situação       1738
dtype: int64

In [9]:
# count null values per row and calculates the averageof null values per row
nan_counts_per_row = formated_df.isna().sum(axis=1)
nan_counts_per_row.describe()

count    3320.000000
mean        1.137048
std         1.074877
min         0.000000
25%         0.000000
50%         1.000000
75%         2.000000
max         6.000000
dtype: float64

In [10]:
formated_df_v2 = formated_df.drop(
    columns=[
        "Período Letivo da Mudança de Situação",
    ]
)

In [11]:
# count null values by column
nan_counts_v2 = formated_df_v2.isna().sum()
nan_counts_v2

Fluxo Escolar - Label                         0
Campus (Nome)                                 0
Matrícula retida?                             0
Ingressantes em (Período Letivo)              0
Modalidade do Curso                           0
Nível de Ensino                               0
Tipo de Modalidade (grupo)                  580
Cidade Aluno                                 78
Cód. da Matriz                                0
Cód. do Curso                                 0
Data Final Período                            3
Data Início Período                           4
Data Última Alteração Matrícula               0
Dt Ref Início Matrícula                       0
Dt Ref Início Período Letivo                  0
Estado Aluno                                 78
Estrutura Etária                              0
Etnia                                         0
Faixa Etária                                  0
Forma de Ingresso                             0
Forma de Oferta (grupo)                       0
Ingressantes em  (Ano Letivo)                 0
Num Seq deste Período Letivo                  0
Periodo Letivo (Num)                          0
Previsão de Término (Letivo)                  0
Reserva vaga                                373
Sexo                                          0
Tipo de Modalidade                          580
Tipo_Escola_Origem                          341
É matrícula retida neste período letivo?      0
Última Alteração de Situação                  0
CH                                            0
CH. Disc. Obrigatórias                        0
CH. Disc. Optativas                           0
Duracao curso                                 0
Idade (Hoje)                                  0
Periodos Cursados                             0
dtype: int64

In [12]:
# count null values per row and calculates the averageof null values per row
nan_counts_per_row_v2 = formated_df_v2.isna().sum(axis=1)
nan_counts_per_row_v2.describe()

count    3320.000000
mean        0.613554
std         0.989427
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         5.000000
dtype: float64

In [21]:
formated_df = formated_df_v2.dropna()
df = formated_df
df.index.name = "indice"

In [22]:
df.loc[df["Fluxo Escolar - Label"] == "Em Curso"]

,Fluxo Escolar - Label,Campus (Nome),Matrícula retida?,Ingressantes em (Período Letivo),Modalidade do Curso,Nível de Ensino,Tipo de Modalidade (grupo),Cidade Aluno,Cód. da Matriz,Cód. do Curso,...,Tipo de Modalidade,Tipo_Escola_Origem,É matrícula retida neste período letivo?,Última Alteração de Situação,CH,CH. Disc. Obrigatórias,CH. Disc. Optativas,Duracao curso,Idade (Hoje),Periodos Cursados
indice,,,,,,,,,,,,,,,,,,,,,
6,Em Curso,Acaraú,Dentro do prazo,20192,Licenciatura,Graduação,Regular,Itarema,12166,11401,...,Regular,E,Não Retida,2019-08-28,2800,2800,0,8,20,1
8,Em Curso,Acaraú,Dentro do prazo,20182,Licenciatura,Graduação,Regular,Marco,4017,11400,...,Regular,E,Não Retida,2019-10-02,2960,2960,0,8,21,4
9,Em Curso,Acaraú,Dentro do prazo,20172,Licenciatura,Graduação,Regular,Acaraú,7334,11401,...,Regular,E,Não Retida,2019-06-07,3200,3200,0,8,36,6
10,Em Curso,Acaraú,Dentro do prazo,20181,Licenciatura,Graduação,Regular,Itarema,4017,11400,...,Regular,E,Não Retida,2019-08-22,2960,2960,0,8,35,4
15,Em Curso,Acaraú,Dentro do prazo,20192,Licenciatura,Graduação,Regular,Cruz,4017,11400,...,Regular,E,Não Retida,2019-09-05,2960,2960,0,8,21,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3304,Em Curso,Acaraú,Dentro do prazo,20191,Subsequente,Técnico,Educação Profissional,Acaraú,5929,11203,...,Educação Profissional,E,Não Retida,2019-04-30,800,800,0,2,26,2
3306,Em Curso,Acaraú,Dentro do prazo,20191,Subsequente,Técnico,Educação Profissional,Acaraú,7083,11204,...,Educação Profissional,E,Não Retida,2019-05-02,800,800,0,2,19,2
3307,Em Curso,Acaraú,Dentro do prazo,20191,Subsequente,Técnico,Educação Profissional,Itarema,5158,11200,...,Educação Profissional,E,Não Retida,2019-04-26,1240,1240,0,4,20,2
3309,Em Curso,Acaraú,Dentro do prazo,20182,Subsequente,Técnico,Educação Profissional,Itarema,6427,11201,...,Educação Profissional,E,Não Retida,2018-10-26,1080,1080,0,4,21,3
3314,Em Curso,Acaraú,Dentro do prazo,20181,Subsequente,Técnico,Educação Profissional,Acaraú,5158,11200,...,Educação Profissional,E,Não Retida,2018-11-19,1240,1240,0,4,33,4

In [23]:
in_course = df.loc[df["Fluxo Escolar - Label"] == "Em Curso"]
graduated = df.loc[df["Fluxo Escolar - Label"] == "Formados"]
dropout = df.loc[df["Fluxo Escolar - Label"] == "Evadidos"]
not_in_course = df.loc[df["Fluxo Escolar - Label"] != "Em Curso"]

In [24]:
in_course.to_csv("./outputs/in_course.csv")
graduated.to_csv("./outputs/graduated.csv")
dropout.to_csv("./outputs/dropout.csv")
not_in_course.to_csv("./outputs/not_in_course.csv")

In [25]:
# Save DataFrame on the data folder
df.to_excel("./data/data_for_training.ods")