In [71]:
import python_calamine
import pandas as pd
import numpy as np
from pandas import DataFrame
from pyexcel_ods import save_data
from collections import OrderedDict

In [72]:
acarau_dataset = pd.read_excel("./data/original_data_aracau.ods", engine="odf")
iguatu_dataset = pd.read_excel("./data/original_data_iguatu.xlsx", engine="calamine")
quixada_dataset = pd.read_excel("./data/original_data_quixada.xlsx", engine="calamine")

In [78]:
colunas_em_comum = set(acarau_dataset.columns).intersection(iguatu_dataset.columns).intersection(quixada_dataset.columns)
len(colunas_em_comum)

48

In [63]:
colunas = set(acarau_dataset.columns).union(iguatu_dataset.columns).union(quixada_dataset.columns)

In [64]:
colunas_exclusivas = colunas.difference(colunas_em_comum)

In [65]:
exclusivas_acarau = colunas_exclusivas.intersection(acarau_dataset.columns)
exclusivas_iguatu = colunas_exclusivas.intersection(iguatu_dataset.columns)
exclusivas_quixada = colunas_exclusivas.intersection(quixada_dataset.columns)

In [77]:
exclusivas_quixada

19

In [76]:
exclusivas_iguatu

19

In [8]:
acarau_dataset

,Unnamed: 0,Fluxo Escolar - Label,Campus (Nome),Curso+Modalidade,Matrícula retida?,Ingressantes em (Período Letivo),Modalidade de Ensino,Modalidade do Curso,Nível de Ensino,Período Letivo,...,É ingressante? (rótulo),É matrícula retida neste período letivo?,Última Alteração de Situação,CH,CH. Disc. Obrigatórias,CH. Disc. Optativas,Duracao curso,Idade (Hoje),Periodos Cursados,Período Letivo da Mudança de Situação
0,0,Em Curso,Acaraú,LÍNGUA INGLESA,Dentro do prazo,20192,Presencial,Fic,Básico,2019/2,...,Ingressante,Não Retida,2019-11-07,160,160,0,2,35,1,2019/2
1,2,Evadidos,Acaraú,TÉCNICO EM AQUICULTURA (Subsequente),Dentro do prazo,20151,Presencial,Subsequente,Técnico,2015/2,...,Veterano,Não Retida,2016-02-26,1240,1240,0,4,28,2,2015/2
2,3,Formados,Acaraú,XADREZ BÁSICO,Dentro do prazo,20172,Presencial,Fic,Básico,2017/2,...,Ingressante,Não Retida,2018-05-16,60,60,0,1,22,1,2017/2
3,5,Formados,Acaraú,TÉCNICO EM EVENTOS (Subsequente),Fora do prazo,20172,Presencial,Subsequente,Técnico,2017/2,...,Ingressante,Não Retida,2018-11-09,800,800,0,2,23,2,NaN
4,7,Evadidos,Acaraú,LICENCIATURA EM CIÊNCIAS BIOLÓGICAS,Dentro do prazo,20152,Presencial,Licenciatura,Graduação,2016/1,...,Veterano,Não Retida,2016-12-01,2940,2860,80,8,23,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3315,8434,Formados,Acaraú,MATEMÁTICA BÁSICA,Dentro do prazo,20182,Presencial,Fic,Básico,2018/2,...,Ingressante,Não Retida,2019-05-09,40,40,0,1,21,1,2018/2
3316,8435,Em Curso,Acaraú,LÍNGUA INGLESA,Dentro do prazo,20192,Presencial,Fic,Básico,2019/2,...,Ingressante,Não Retida,2019-10-16,160,160,0,2,26,1,NaN
3317,8437,Evadidos,Acaraú,LÍNGUA INGLESA,Fora do prazo,20172,Presencial,Fic,Básico,2018/1,...,Veterano,Retida,2018-06-19,160,160,0,2,28,2,2018/1
3318,8443,Formados,Acaraú,TÉCNICO EM AQUICULTURA (Subsequente),Fora do prazo,20161,Presencial,Subsequente,Técnico,2018/2,...,Veterano,Retida,2018-12-28,1240,1240,0,4,22,6,2018/2
3319,8445,Evadidos,Acaraú,LICENCIATURA EM CIÊNCIAS BIOLÓGICAS,Dentro do prazo,20182,Presencial,Licenciatura,Graduação,2018/2,...,Ingressante,Não Retida,2019-06-14,3440,3200,240,8,19,2,NaN

In [9]:
iguatu_dataset

,Unnamed: 0,Fluxo Escolar - Label,Campus (Nome),Curso+Modalidade,Matrícula retida?,Tipo de Situação de Matrícula,Ingressantes em (Período Letivo),Modalidade de Ensino,Modalidade do Curso,Nível de Ensino,...,CH. Disc. Obrigatórias,CH. Disc. Optativas,Duracao curso,Idade (Hoje),Periodos Cursados,Período Letivo da Mudança de Situação,Qtde cursos,Qtde Ingressantes,Qtde Matriculados,Qtde Matriculados (em curso)
0,4,Evadidos,Iguatu,TÉCNICO EM INFORMÁTICA (Subsequente),Fora do prazo,Egresso sem êxito,20152,Presencial,Subsequente,Técnico,...,1040,0,3,25,5,2017/2,1,0,1,0
1,10,Em Curso,Iguatu,LICENCIATURA EM QUÍMICA,Dentro do prazo,Em curso,20171,Presencial,Licenciatura,Graduação,...,3160,0,9,22,7,NaN,1,1,1,1
2,11,Formados,Iguatu,OPERADOR DE COMPUTADOR,Dentro do prazo,Egresso com êxito,20152,Presencial,Fic,Básico,...,160,0,1,42,1,2015/2,1,1,1,0
3,12,Em Curso,Iguatu,ESPECIALIZAÇÃO EM EDUCAÇÃO PROFISSIONAL,Dentro do prazo,Em curso,20182,Presencial,Especialização,Pós-graduação,...,360,0,3,31,1,NaN,1,1,1,1
4,15,Retidos,Iguatu,TÉCNICO EM INFORMÁTICA (Subsequente),Fora do prazo,Em curso,20182,Presencial,Subsequente,Técnico,...,1040,0,3,34,4,NaN,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,11359,Formados,Iguatu,TÉCNICO EM NUTRIÇÃO E DIETÉTICA (Subsequente),Dentro do prazo,Egresso com êxito,20171,Presencial,Subsequente,Técnico,...,1200,0,3,54,4,2018/2,1,0,1,0
3906,11360,Evadidos,Iguatu,ÉTICA EM MOVIMENTO: FORMAÇÃO ÉTICA PARA ASSIST...,Dentro do prazo,Egresso sem êxito,20192,Presencial,Fic,Básico,...,40,0,1,48,1,2019/2,1,1,1,0
3907,11361,Evadidos,Iguatu,TÉCNICO EM AGROINDÚSTRIA (Integrado),Dentro do prazo,Egresso sem êxito,20161,Presencial,Integrado,Técnico,...,3640,0,6,21,1,2016/1,1,1,1,0
3908,11362,Evadidos,Iguatu,TÉCNICO EM NUTRIÇÃO E DIETÉTICA (Integrado),Dentro do prazo,Egresso sem êxito,20191,Presencial,Integrado,Técnico,...,3640,0,6,17,1,NaN,1,1,1,0
3909,11367,Evadidos,Iguatu,TÉCNICO EM ZOOTECNIA (Subsequente),Fora do prazo,Egresso sem êxito,20171,Presencial,Subsequente,Técnico,...,1200,0,3,24,5,NaN,1,1,1,0

In [10]:
quixada_dataset

,Unnamed: 0,Fluxo Escolar - Label,Campus (Nome),Curso+Modalidade,Matrícula retida?,Tipo de Situação de Matrícula,Ingressantes em (Período Letivo),Modalidade de Ensino,Modalidade do Curso,Nível de Ensino,...,CH. Disc. Obrigatórias,CH. Disc. Optativas,Duracao curso,Idade (Hoje),Periodos Cursados,Período Letivo da Mudança de Situação,Qtde cursos,Qtde Ingressantes,Qtde Matriculados,Qtde Matriculados (em curso)
0,0,Em Curso,Quixadá,BACHARELADO EM ENGENHARIA AMBIENTAL,Dentro do prazo,Em curso,20192,Presencial,Bacharelado,Graduação,...,3600,120,10,23,2,NaN,1,1,1,1
1,8,Em Curso,Quixadá,BACHARELADO EM ENGENHARIA DE PRODUÇÃO CIVIL,Dentro do prazo,Em curso,20161,Presencial,Bacharelado,Graduação,...,3720,40,10,24,9,NaN,1,0,1,1
2,14,Em Curso,Quixadá,LICENCIATURA EM GEOGRAFIA,Dentro do prazo,Em curso,20171,Presencial,Licenciatura,Graduação,...,3280,0,9,27,7,2017/1,1,1,1,1
3,22,Em Curso,Quixadá,LICENCIATURA EM GEOGRAFIA,Dentro do prazo,Em curso,20161,Presencial,Licenciatura,Graduação,...,3280,0,9,30,9,NaN,1,0,1,1
4,24,Evadidos,Quixadá,TÉCNICO EM EDIFICAÇÕES (Concomitante),Dentro do prazo,Egresso sem êxito,20151,Presencial,Concomitante,Técnico,...,1520,0,4,24,2,2015/2,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,11127,Evadidos,Quixadá,TÉCNICO EM MULTIMEIOS DIDÁTICOS (Subsequente),Dentro do prazo,Egresso sem êxito,20152,A Distância,Subsequente,Técnico,...,1280,0,4,45,3,2016/2,1,0,1,0
3218,11134,Em Curso,Quixadá,BACHARELADO EM ENGENHARIA DE PRODUÇÃO CIVIL,Dentro do prazo,Em curso,20162,Presencial,Bacharelado,Graduação,...,3720,40,10,22,8,NaN,1,0,1,1
3219,11138,Em Curso,Quixadá,BACHARELADO EM ENGENHARIA AMBIENTAL,Dentro do prazo,Em curso,20181,Presencial,Bacharelado,Graduação,...,3600,120,10,21,4,NaN,1,1,1,1
3220,11139,Evadidos,Quixadá,TÉCNICO EM SECRETARIA ESCOLAR (Subsequente),Dentro do prazo,Egresso sem êxito,20152,A Distância,Subsequente,Técnico,...,1380,0,4,35,1,2015/2,1,1,1,0
3221,11140,Evadidos,Quixadá,TÉCNICO EM SECRETARIA ESCOLAR (Subsequente),Dentro do prazo,Egresso sem êxito,20152,A Distância,Subsequente,Técnico,...,1380,0,4,52,1,2015/2,1,1,1,0

In [83]:
colunas_novo_dataset = list(colunas_em_comum)

In [84]:
acarau_filtrado = acarau_dataset[colunas_novo_dataset]
quixada_filtrado = quixada_dataset[colunas_novo_dataset]
iguatu_filtrado = iguatu_dataset[colunas_novo_dataset]

In [85]:
novo_dataset = pd.concat([acarau_filtrado, quixada_filtrado, iguatu_filtrado])

In [86]:
novo_dataset

,Estrutura Etária,Tipo de Modalidade,Periodos Cursados,Município do Campus,Fluxo Escolar - Label,Sexo,Dt Ref Início Período Letivo,Campus (Nome),Período Letivo da Mudança de Situação,Periodo Letivo (Num),...,Idade (Hoje),Faixa Etária,Data Início Período,Cód. do Curso,Última Alteração de Situação,Data Última Alteração Matrícula,Nível de Ensino,CH. Disc. Optativas,Matrícula retida?,Tipo de Modalidade (grupo)
0,Adulto (20 a 59 anos),NaN,1,ACARAÚ,Em Curso,F,2019-01-07 00:00:00,Acaraú,2019/2,20192,...,35,35 a 39 anos,2019-11-04 00:00:00,111024,2019-11-07 00:00:00,2019-11-07 00:00:00,Básico,0,Dentro do prazo,NaN
1,Adulto (20 a 59 anos),Educação Profissional,2,ACARAÚ,Evadidos,F,2015-01-07 00:00:00,Acaraú,2015/2,20152,...,28,25 a 29 anos,2016-01-25 00:00:00,11200,2016-02-26 00:00:00,2016-02-26 11:13:00,Técnico,0,Dentro do prazo,Educação Profissional
2,Adulto (20 a 59 anos),NaN,1,ACARAÚ,Formados,M,2017-01-07 00:00:00,Acaraú,2017/2,20172,...,22,20 a 24 anos,2018-01-24 00:00:00,111030,2018-05-16 00:00:00,2018-05-16 00:00:00,Básico,0,Dentro do prazo,NaN
3,Adulto (20 a 59 anos),Educação Profissional,2,ACARAÚ,Formados,M,2017-01-07 00:00:00,Acaraú,NaN,20172,...,23,20 a 24 anos,2017-11-16 00:00:00,11204,2018-11-09 00:00:00,2018-11-09 00:00:00,Técnico,0,Fora do prazo,Educação Profissional
4,Adulto (20 a 59 anos),Regular,2,ACARAÚ,Evadidos,F,2016-01-01 00:00:00,Acaraú,NaN,20161,...,23,20 a 24 anos,2016-06-22 00:00:00,11401,2016-12-01 00:00:00,2016-12-01 13:35:00,Graduação,80,Dentro do prazo,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,Adulto (20 a 59 anos),Educação Profissional,4,IGUATU,Formados,M,43107,Iguatu,2018/2,20182,...,54,50 a 54 anos,43346.0,9226,43355,2018-09-12 00:00:00,Técnico,0,Dentro do prazo,Educação Profissional
3906,Adulto (20 a 59 anos),NaN,1,IGUATU,Evadidos,F,43472,Iguatu,2019/2,20192,...,48,45 a 49 anos,43746.0,91027,43747,2019-10-09 00:00:00,Básico,0,Dentro do prazo,NaN
3907,Adulto (20 a 59 anos),Educação Profissional,1,IGUATU,Evadidos,M,42370,Iguatu,2016/1,20161,...,21,20 a 24 anos,42445.0,9114,42479,2016-04-19 08:36:00,Técnico,0,Dentro do prazo,Educação Profissional
3908,Jovem (<= 19 anos),Educação Profissional,1,IGUATU,Evadidos,F,43466,Iguatu,NaN,20191,...,17,15 a 19 anos,43521.0,9116,43496,2019-01-31 11:11:00,Técnico,0,Dentro do prazo,Educação Profissional
3909,Adulto (20 a 59 anos),Educação Profissional,5,IGUATU,Evadidos,F,42736,Iguatu,NaN,20171,...,24,20 a 24 anos,42821.0,9210,43564,2019-04-09 17:01:00,Técnico,0,Fora do prazo,Educação Profissional

In [88]:
novo_dataset.to_csv("./data/out_novo_dataset.csv")